/* ============================================================================
 * Copyright (c) 2008-2016 Texas Instruments Incorporated.
 * 
 *  Redistribution and use in source and binary forms, with or without 
 *  modification, are permitted provided that the following conditions 
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright 
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the 
 *    documentation and/or other materials provided with the   
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
*/


/** @file csl_pll_ldo_setting_example.c
 *
 *  @brief Example to dynamically set PLL and LDO values
 *
 *
 * \page    page14  CSL PLL EXAMPLE DOCUMENTATION
 *
 * \section PLL2   PLL EXAMPLE2 - PLL LDO SETTING EXAMPLE
 *
 * \subsection PLL2x    TEST DESCRIPTION:
 *        This test code verifies the functionality of CSL PLL and LDO module.
 * LDO module on the C5535/C5515/C5517 DSP is used to set the DSP_LDO voltage
 * levels to either 1.05V or 1.30V. PLL module on the C5535/C5515/C5517 DSP is
 * used to generate clock for CPU and peripherals. A 32KHz input clock is
 * supplied to the PLL using which different system clock values are generated.
 * Different system clock values are generated by configuring the PLL to
 * different divider values.
 *
 * During the test the DSP_LDO voltage will be set to either 1.05V or 1.30V and
 * later the PLL module will be configured to the 60MHz clock frequency using
 * PLL_config() API. Configured values are read back and verified using
 * PLL_getConfig() APIs. All the values should match the configured values
 * except the test lock mon value which will reflect on the registers only
 * after the PLL is up. Values read from the PLL are displayed on the CCS
 * "stdout" window. Manual inspection is required to verify the test success.
 *
 * C5515 DSP PLL register bit fields are little different than that of C5535
 * DSP. Use the 'PLL_Config' values defined 12.288MHz - 120MHz to verify PLL
 * configuration.
 * C5517 DSP PLL register bit fields are different, too. Use the 'PLL_Config'
 * values defined 12.288MHz-200MHz to verify PLL configuration
 *
 * NOTE: THIS TEST HAS BEEN DEVELOPED TO WORK WITH CHIP VERSIONS C5535, C5515
 * AND C5517. MAKE SURE THAT PROPER CHIP VERSION MACRO IS DEFINED IN THE FILE
 * c55xx_csl\inc\csl_general.h.
 *
 * \subsection PLL2y    TEST PROCEDURE:
 *  @li Open the CCS and connect the target (C5535/C5515/C5517 EVM)
 *  @li Open the project "CSL_PLL_LDO_Setting_Example.pjt" and build it
 *  @li Load the program on to the target
 *  @li Run the program and observe the test result
 *  @li Repeat the test at the following PLL frequencies
 *      C5515: 60MHz and 100MHz
 *      C5517: 60MHz, 100MHz, 150MHz and 200MHz
 *      C5535 eZdsp: 60MHz and 100MHz
 *  @li Repeat the test in Release mode
 *
 * \subsection PLL2z    TEST RESULT:
 *  @li All the CSL APIs should return success
 *  @li Configuration values read from the PLL should match with the actual
 *      configured values except the test lock mon value, for both the LDO
 *      voltage levels.
 *
 */

/* ============================================================================
 * Revision History
 * ================
 * 07-Feb-2013 Created
 * 09-Mar-2016 Update the header
 * ============================================================================
 */

#include<stdio.h>
#include "csl_pll.h"
#include "csl_general.h"
#include "csl_pllAux.h"
#include "cslr_sysctrl.h"
#include "csl_sysctrl.h"

PLL_Obj pllObj;
PLL_Config pllCfg1;

PLL_Handle hPll;

#if (defined(CHIP_C5505_C5515) || defined(CHIP_C5504_C5514) || defined(CHIP_C5535) || defined(CHIP_C5545))

PLL_Config pllCfg_config_1 = {0x8173, 0x8000, 0x0806, 0x0000};
/**< PLL Configuration values to set the CPU clock as 12.288 MHz  */
PLL_Config pllCfg_config_2 = {0x8988, 0x8000, 0x0806, 0x0201};
/**< PLL Configuration values to set the CPU clock as 40 MHz      */
PLL_Config pllCfg_config_3 = {0x8724, 0x8000, 0x0806, 0x0000};
/**< PLL Configuration values to set the CPU clock as 60 MHz      */
PLL_Config pllCfg_config_4 = {0x88ED, 0x8000, 0x0806, 0x0000};
/**< PLL Configuration values to set the CPU clock as 75 MHz      */
PLL_Config pllCfg_config_5 = {0x8BE8, 0x8000, 0x0806, 0x0000};
/**< PLL Configuration values to set the CPU clock as 100 MHz     */
PLL_Config pllCfg_config_6 = {0x8E4A, 0x8000, 0x0806, 0x0000};
/**< PLL Configuration values to set the CPU clock as 120 MHz     */

#elif defined(CHIP_C5517)

PLL_Config pllCfg_config_1 = {0x28AB, 0x0003, 0x0000, 0x0024};
/**< PLL Configuration values to set the CPU clock as 25 MHz      */
PLL_Config pllCfg_config_2 = {0x3100, 0x0003, 0x0000, 0x0022};
/**< PLL Configuration values to set the CPU clock as 50 MHz      */
PLL_Config pllCfg_config_3 = {0x41AB, 0x0003, 0x0000, 0x0000};
/**< PLL Configuration values to set the CPU clock as 100 MHz     */
PLL_Config pllCfg_config_4 = {0x3100, 0x0003, 0x0000, 0x0020};
/**< PLL Configuration values to set the CPU clock as 150 MHz     */
PLL_Config pllCfg_config_5 = {0x3956, 0x0003, 0x0000, 0x0020};
/**< PLL Configuration values to set the CPU clock as 175 MHz     */
PLL_Config pllCfg_config_6 = {0x41AB, 0x0003, 0x0000, 0x0020};
/**< PLL Configuration values to set the CPU clock as 200 MHz     */

#else

PLL_Config pllCfg_config_1 = {0x82ED, 0x8000, 0x0806, 0x0200};
/**< PLL Configuration values to set the CPU clock as 12.288 MHz  */
PLL_Config pllCfg_config_2 = {0x8262, 0x8000, 0x0806, 0x0300};
/**< PLL Configuration values to set the CPU clock as 40 MHz      */
PLL_Config pllCfg_config_3 = {0x81C8, 0xB000, 0x0806, 0x0000};
/**< PLL Configuration values to set the CPU clock as 60 MHz      */
PLL_Config pllCfg_config_4 = {0x823B, 0x9000, 0x0806, 0x0000};
/**< PLL Configuration values to set the CPU clock as 75 MHz      */
PLL_Config pllCfg_config_5 = {0x82FA, 0x8000, 0x0806, 0x0000};
/**< PLL Configuration values to set the CPU clock as 100 MHz     */
PLL_Config pllCfg_config_6 = {0x8392, 0xA000, 0x0806, 0x0000};
/**< PLL Configuration values to set the CPU clock as 120 MHz     */

#endif

#define NO_OF_CONFIGURATIONS (6)
/**< Total Number of PLL configurations that will be used         */

PLL_Config *pConfigInfo[NO_OF_CONFIGURATIONS] = {&pllCfg_config_1,
                                                 &pllCfg_config_2,
                                                 &pllCfg_config_3,
                                                 &pllCfg_config_4,
                                                 &pllCfg_config_5,
                                                 &pllCfg_config_6};
/**< Array of pointers to the PLL config structures               */

#define CSL_TEST_FAILED         (1)
/**< Value to indicate that the Test has Failed                   */
#define CSL_TEST_PASSED         (0)
/**< Value to indicate that the Test has Passed                   */

/**
 * \brief Function to set the PLL values, read them back and validate them
 *
 * \param NONE
 *
 * \return Error Status
 */
CSL_Status pll_ldo_sample()
{
    CSL_Status status;
    Uint16     looper;
    Uint32     currentSysClock;

    status = PLL_init(&pllObj, CSL_PLL_INST_0);
    if(CSL_SOK != status)
    {
       printf("PLL init failed \n");
       return (status);
    }

    hPll = (PLL_Handle)(&pllObj);

    PLL_reset(hPll);

    for (looper = 0; looper < NO_OF_CONFIGURATIONS; looper++)
    {
        currentSysClock = 0;

        status = PLL_config (hPll, pConfigInfo[looper]);
        if(CSL_SOK != status)
        {
            printf("PLL config failed\n");
            return(status);
        }

        status = PLL_getConfig(hPll, &pllCfg1);
        if(status != CSL_SOK)
        {
            printf("TEST FAILED: PLL get config... Failed.\n");
            printf ("Reason: PLL_getConfig failed. [status = 0x%x].\n", status);
            return(status);
        }

        printf("\n\nREGISTER --- CONFIG VALUES\n");

#if (defined(CHIP_C5517))
        printf("%04x --- %04x\n",pllCfg1.PLLMR,hPll->pllConfig->PLLMR);
        printf("%04x --- %04x\n",pllCfg1.PLLICR,hPll->pllConfig->PLLICR);
        printf("%04x --- %04x\n",pllCfg1.PLLODR,hPll->pllConfig->PLLODR);
#else
        printf("%04x --- %04x\n", pllCfg1.PLLCNTL1, hPll->pllConfig->PLLCNTL1);
        printf("%04x --- %04x Test Lock Mon will get set after PLL is up\n",
               pllCfg1.PLLCNTL2,hPll->pllConfig->PLLCNTL2);
        printf("%04x --- %04x\n",pllCfg1.PLLINCNTL,hPll->pllConfig->PLLINCNTL);
        printf("%04x --- %04x\n",pllCfg1.PLLOUTCNTL,hPll->pllConfig->PLLOUTCNTL);
#endif

        currentSysClock = getSysClk();

        printf ("Current SYSTEM CLOCK is : %ld kHz\n", currentSysClock);

        status = PLL_bypass(hPll);
        if(CSL_SOK != status)
        {
            printf("PLL bypass failed:%d\n",CSL_ESYS_BADHANDLE);
            return(status);
        }

        status = PLL_enable(hPll);
        if(CSL_SOK != status)
        {
            printf("PLL enable failed:%d\n",CSL_ESYS_BADHANDLE);
            return(status);
        }
    }

    return (CSL_TEST_PASSED);
}

   /////INSTRUMENTATION FOR BATCH TESTING -- Part 1 --
   /////  Define PaSs_StAtE variable for catching errors as program executes.
   /////  Define PaSs flag for holding final pass/fail result at program completion.
        volatile Int16 PaSs_StAtE = 0x0001; // Init to 1. Reset to 0 at any monitored execution error.
        volatile Int16 PaSs = 0x0000; // Init to 0.  Updated later with PaSs_StAtE when and if
   /////                                  program flow reaches expected exit point(s).
   /////
void main(void)
{
    CSL_Status status;

    status  = CSL_TEST_PASSED;

    printf("CSL PLL TEST WITH DIFFERENT LDO VOLATGE LEVELS\n\n");

    printf("\nSetting DSP_LDOO voltage to 1.05V\n");
    SYS_set_DSP_LDO_voltage(CSL_DSP_LDO_1pt05_VOLTAGE);

    status = pll_ldo_sample();
    if (CSL_TEST_PASSED != status)
    {
        printf ("\nCSL PLL TEST FAILED for DSP_LDOO voltage as 1.05V\n");
   /////INSTRUMENTATION FOR BATCH TESTING -- Part 2 --
   /////  Resetting PaSs_StAtE to 0 if error detected here.
        PaSs_StAtE = 0x0000; // Was initialized to 1 at declaration.
   /////
    }
    else
    {
        printf ("\nCSL PLL TEST PASSED for DSP_LDOO voltage as 1.05V\n");
    }

    printf("\nSetting DSP_LDOO voltage to 1.30V\n");
    SYS_set_DSP_LDO_voltage(CSL_DSP_LDO_1pt30_VOLTAGE);

    status = pll_ldo_sample();
    if (CSL_TEST_PASSED != status)
    {
        printf ("\nCSL PLL TEST FAILED for DSP_LDOO voltage as 1.30V\n");
   /////INSTRUMENTATION FOR BATCH TESTING -- Part 2 --
   /////  Resetting PaSs_StAtE to 0 if error detected here.
        PaSs_StAtE = 0x0000; // Was initialized to 1 at declaration.
   /////
    }
    else
    {
        printf ("\nCSL PLL TEST PASSED for DSP_LDOO voltage as 1.30V\n");
    }

    printf ("\nCSL PLL TEST WITH DIFFERENT LDO VOLATGE LEVELS COMPLETED\n");

    asm("    nop");
   /////INSTRUMENTATION FOR BATCH TESTING -- Part 3 --
   /////  At program exit, copy "PaSs_StAtE" into "PaSs".
        PaSs = PaSs_StAtE; //If flow gets here, override PaSs' initial 0 with
   /////                   // pass/fail value determined during program execution.
   /////  Note:  Program should next exit to C$$EXIT and halt, where DSS, under
   /////   control of a host PC script, will read and record the PaSs' value.
   /////
}

