/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT BF_rt_bios_.cdb */

/*  Include Header File  */
#include "BF_rt_bios_cfg.h"

/*  Config Structures */
/*  Handles  */
